#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17626
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace thitracnghiem
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QL_Thitracnghiem")]
	public partial class QLTHITNDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertBODETHI(BODETHI instance);
    partial void UpdateBODETHI(BODETHI instance);
    partial void DeleteBODETHI(BODETHI instance);
    partial void InsertSINHVIEN(SINHVIEN instance);
    partial void UpdateSINHVIEN(SINHVIEN instance);
    partial void DeleteSINHVIEN(SINHVIEN instance);
    partial void InsertCAPBAC(CAPBAC instance);
    partial void UpdateCAPBAC(CAPBAC instance);
    partial void DeleteCAPBAC(CAPBAC instance);
    partial void InsertCHITIETBODETHI(CHITIETBODETHI instance);
    partial void UpdateCHITIETBODETHI(CHITIETBODETHI instance);
    partial void DeleteCHITIETBODETHI(CHITIETBODETHI instance);
    partial void InsertCHITIETDETHI(CHITIETDETHI instance);
    partial void UpdateCHITIETDETHI(CHITIETDETHI instance);
    partial void DeleteCHITIETDETHI(CHITIETDETHI instance);
    partial void InsertCHUCVU(CHUCVU instance);
    partial void UpdateCHUCVU(CHUCVU instance);
    partial void DeleteCHUCVU(CHUCVU instance);
    partial void InsertDETHI(DETHI instance);
    partial void UpdateDETHI(DETHI instance);
    partial void DeleteDETHI(DETHI instance);
    partial void InsertDETHI_SINHVIEN(DETHI_SINHVIEN instance);
    partial void UpdateDETHI_SINHVIEN(DETHI_SINHVIEN instance);
    partial void DeleteDETHI_SINHVIEN(DETHI_SINHVIEN instance);
    partial void InsertDONVI(DONVI instance);
    partial void UpdateDONVI(DONVI instance);
    partial void DeleteDONVI(DONVI instance);
    partial void InsertKETQUA(KETQUA instance);
    partial void UpdateKETQUA(KETQUA instance);
    partial void DeleteKETQUA(KETQUA instance);
    partial void InsertKYTHI(KYTHI instance);
    partial void UpdateKYTHI(KYTHI instance);
    partial void DeleteKYTHI(KYTHI instance);
    partial void InsertNHOMVK(NHOMVK instance);
    partial void UpdateNHOMVK(NHOMVK instance);
    partial void DeleteNHOMVK(NHOMVK instance);
    partial void InsertCAUHOI(CAUHOI instance);
    partial void UpdateCAUHOI(CAUHOI instance);
    partial void DeleteCAUHOI(CAUHOI instance);
    partial void InsertDAPAN(DAPAN instance);
    partial void UpdateDAPAN(DAPAN instance);
    partial void DeleteDAPAN(DAPAN instance);
    #endregion
		
		public QLTHITNDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["QL_ThitracnghiemConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public QLTHITNDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLTHITNDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLTHITNDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLTHITNDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<BODETHI> BODETHIs
		{
			get
			{
				return this.GetTable<BODETHI>();
			}
		}
		
		public System.Data.Linq.Table<SINHVIEN> SINHVIENs
		{
			get
			{
				return this.GetTable<SINHVIEN>();
			}
		}
		
		public System.Data.Linq.Table<CAPBAC> CAPBACs
		{
			get
			{
				return this.GetTable<CAPBAC>();
			}
		}
		
		public System.Data.Linq.Table<CHITIETBODETHI> CHITIETBODETHIs
		{
			get
			{
				return this.GetTable<CHITIETBODETHI>();
			}
		}
		
		public System.Data.Linq.Table<CHITIETDETHI> CHITIETDETHIs
		{
			get
			{
				return this.GetTable<CHITIETDETHI>();
			}
		}
		
		public System.Data.Linq.Table<CHUCVU> CHUCVUs
		{
			get
			{
				return this.GetTable<CHUCVU>();
			}
		}
		
		public System.Data.Linq.Table<DETHI> DETHIs
		{
			get
			{
				return this.GetTable<DETHI>();
			}
		}
		
		public System.Data.Linq.Table<DETHI_SINHVIEN> DETHI_SINHVIENs
		{
			get
			{
				return this.GetTable<DETHI_SINHVIEN>();
			}
		}
		
		public System.Data.Linq.Table<DONVI> DONVIs
		{
			get
			{
				return this.GetTable<DONVI>();
			}
		}
		
		public System.Data.Linq.Table<KETQUA> KETQUAs
		{
			get
			{
				return this.GetTable<KETQUA>();
			}
		}
		
		public System.Data.Linq.Table<KYTHI> KYTHIs
		{
			get
			{
				return this.GetTable<KYTHI>();
			}
		}
		
		public System.Data.Linq.Table<LOADKQCU> LOADKQCUs
		{
			get
			{
				return this.GetTable<LOADKQCU>();
			}
		}
		
		public System.Data.Linq.Table<NHOMVK> NHOMVKs
		{
			get
			{
				return this.GetTable<NHOMVK>();
			}
		}
		
		public System.Data.Linq.Table<BODETHI_CAUHOI> BODETHI_CAUHOIs
		{
			get
			{
				return this.GetTable<BODETHI_CAUHOI>();
			}
		}
		
		public System.Data.Linq.Table<CAUHOI> CAUHOIs
		{
			get
			{
				return this.GetTable<CAUHOI>();
			}
		}
		
		public System.Data.Linq.Table<DAPAN> DAPANs
		{
			get
			{
				return this.GetTable<DAPAN>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_DanhSachCauHoiDeThi")]
		public ISingleResult<sp_DanhSachCauHoiDeThiResult> sp_DanhSachCauHoiDeThi([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> madethi)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), madethi);
			return ((ISingleResult<sp_DanhSachCauHoiDeThiResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.BODETHI")]
	public partial class BODETHI : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MABODT;
		
		private System.Nullable<System.DateTime> _NGAYTAO;
		
		private System.Nullable<int> _SOCAUHOI;
		
		private EntitySet<CHITIETBODETHI> _CHITIETBODETHIs;
		
		private EntitySet<KYTHI> _KYTHIs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMABODTChanging(int value);
    partial void OnMABODTChanged();
    partial void OnNGAYTAOChanging(System.Nullable<System.DateTime> value);
    partial void OnNGAYTAOChanged();
    partial void OnSOCAUHOIChanging(System.Nullable<int> value);
    partial void OnSOCAUHOIChanged();
    #endregion
		
		public BODETHI()
		{
			this._CHITIETBODETHIs = new EntitySet<CHITIETBODETHI>(new Action<CHITIETBODETHI>(this.attach_CHITIETBODETHIs), new Action<CHITIETBODETHI>(this.detach_CHITIETBODETHIs));
			this._KYTHIs = new EntitySet<KYTHI>(new Action<KYTHI>(this.attach_KYTHIs), new Action<KYTHI>(this.detach_KYTHIs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MABODT", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MABODT
		{
			get
			{
				return this._MABODT;
			}
			set
			{
				if ((this._MABODT != value))
				{
					this.OnMABODTChanging(value);
					this.SendPropertyChanging();
					this._MABODT = value;
					this.SendPropertyChanged("MABODT");
					this.OnMABODTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAYTAO", DbType="Date")]
		public System.Nullable<System.DateTime> NGAYTAO
		{
			get
			{
				return this._NGAYTAO;
			}
			set
			{
				if ((this._NGAYTAO != value))
				{
					this.OnNGAYTAOChanging(value);
					this.SendPropertyChanging();
					this._NGAYTAO = value;
					this.SendPropertyChanged("NGAYTAO");
					this.OnNGAYTAOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SOCAUHOI", DbType="Int")]
		public System.Nullable<int> SOCAUHOI
		{
			get
			{
				return this._SOCAUHOI;
			}
			set
			{
				if ((this._SOCAUHOI != value))
				{
					this.OnSOCAUHOIChanging(value);
					this.SendPropertyChanging();
					this._SOCAUHOI = value;
					this.SendPropertyChanged("SOCAUHOI");
					this.OnSOCAUHOIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="BODETHI_CHITIETBODETHI", Storage="_CHITIETBODETHIs", ThisKey="MABODT", OtherKey="MABODT")]
		public EntitySet<CHITIETBODETHI> CHITIETBODETHIs
		{
			get
			{
				return this._CHITIETBODETHIs;
			}
			set
			{
				this._CHITIETBODETHIs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="BODETHI_KYTHI", Storage="_KYTHIs", ThisKey="MABODT", OtherKey="MABODT")]
		public EntitySet<KYTHI> KYTHIs
		{
			get
			{
				return this._KYTHIs;
			}
			set
			{
				this._KYTHIs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CHITIETBODETHIs(CHITIETBODETHI entity)
		{
			this.SendPropertyChanging();
			entity.BODETHI = this;
		}
		
		private void detach_CHITIETBODETHIs(CHITIETBODETHI entity)
		{
			this.SendPropertyChanging();
			entity.BODETHI = null;
		}
		
		private void attach_KYTHIs(KYTHI entity)
		{
			this.SendPropertyChanging();
			entity.BODETHI = this;
		}
		
		private void detach_KYTHIs(KYTHI entity)
		{
			this.SendPropertyChanging();
			entity.BODETHI = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SINHVIEN")]
	public partial class SINHVIEN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MATS;
		
		private string _HOTEN;
		
		private System.Nullable<int> _CAPBAC;
		
		private System.Nullable<int> _CHUCVU;
		
		private System.Nullable<int> _DONVI;
		
		private string _TENDN;
		
		private string _MATKHAU;
		
		private System.Nullable<int> _SODETHI;
		
		private System.Nullable<int> _TENBAITH;
		
		private EntityRef<CAPBAC> _CAPBAC1;
		
		private EntityRef<CHUCVU> _CHUCVU1;
		
		private EntityRef<DETHI> _DETHI;
		
		private EntityRef<DONVI> _DONVI1;
		
		private EntityRef<NHOMVK> _NHOMVK;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMATSChanging(int value);
    partial void OnMATSChanged();
    partial void OnHOTENChanging(string value);
    partial void OnHOTENChanged();
    partial void OnCAPBACChanging(System.Nullable<int> value);
    partial void OnCAPBACChanged();
    partial void OnCHUCVUChanging(System.Nullable<int> value);
    partial void OnCHUCVUChanged();
    partial void OnDONVIChanging(System.Nullable<int> value);
    partial void OnDONVIChanged();
    partial void OnTENDNChanging(string value);
    partial void OnTENDNChanged();
    partial void OnMATKHAUChanging(string value);
    partial void OnMATKHAUChanged();
    partial void OnSODETHIChanging(System.Nullable<int> value);
    partial void OnSODETHIChanged();
    partial void OnTENBAITHChanging(System.Nullable<int> value);
    partial void OnTENBAITHChanged();
    #endregion
		
		public SINHVIEN()
		{
			this._CAPBAC1 = default(EntityRef<CAPBAC>);
			this._CHUCVU1 = default(EntityRef<CHUCVU>);
			this._DETHI = default(EntityRef<DETHI>);
			this._DONVI1 = default(EntityRef<DONVI>);
			this._NHOMVK = default(EntityRef<NHOMVK>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MATS", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MATS
		{
			get
			{
				return this._MATS;
			}
			set
			{
				if ((this._MATS != value))
				{
					this.OnMATSChanging(value);
					this.SendPropertyChanging();
					this._MATS = value;
					this.SendPropertyChanged("MATS");
					this.OnMATSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HOTEN", DbType="NVarChar(50)")]
		public string HOTEN
		{
			get
			{
				return this._HOTEN;
			}
			set
			{
				if ((this._HOTEN != value))
				{
					this.OnHOTENChanging(value);
					this.SendPropertyChanging();
					this._HOTEN = value;
					this.SendPropertyChanged("HOTEN");
					this.OnHOTENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CAPBAC", DbType="Int")]
		public System.Nullable<int> CAPBAC
		{
			get
			{
				return this._CAPBAC;
			}
			set
			{
				if ((this._CAPBAC != value))
				{
					if (this._CAPBAC1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCAPBACChanging(value);
					this.SendPropertyChanging();
					this._CAPBAC = value;
					this.SendPropertyChanged("CAPBAC");
					this.OnCAPBACChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CHUCVU", DbType="Int")]
		public System.Nullable<int> CHUCVU
		{
			get
			{
				return this._CHUCVU;
			}
			set
			{
				if ((this._CHUCVU != value))
				{
					if (this._CHUCVU1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCHUCVUChanging(value);
					this.SendPropertyChanging();
					this._CHUCVU = value;
					this.SendPropertyChanged("CHUCVU");
					this.OnCHUCVUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DONVI", DbType="Int")]
		public System.Nullable<int> DONVI
		{
			get
			{
				return this._DONVI;
			}
			set
			{
				if ((this._DONVI != value))
				{
					if (this._DONVI1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnDONVIChanging(value);
					this.SendPropertyChanging();
					this._DONVI = value;
					this.SendPropertyChanged("DONVI");
					this.OnDONVIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENDN", DbType="NVarChar(20)")]
		public string TENDN
		{
			get
			{
				return this._TENDN;
			}
			set
			{
				if ((this._TENDN != value))
				{
					this.OnTENDNChanging(value);
					this.SendPropertyChanging();
					this._TENDN = value;
					this.SendPropertyChanged("TENDN");
					this.OnTENDNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MATKHAU", DbType="NVarChar(20)")]
		public string MATKHAU
		{
			get
			{
				return this._MATKHAU;
			}
			set
			{
				if ((this._MATKHAU != value))
				{
					this.OnMATKHAUChanging(value);
					this.SendPropertyChanging();
					this._MATKHAU = value;
					this.SendPropertyChanged("MATKHAU");
					this.OnMATKHAUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SODETHI", DbType="Int")]
		public System.Nullable<int> SODETHI
		{
			get
			{
				return this._SODETHI;
			}
			set
			{
				if ((this._SODETHI != value))
				{
					if (this._DETHI.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnSODETHIChanging(value);
					this.SendPropertyChanging();
					this._SODETHI = value;
					this.SendPropertyChanged("SODETHI");
					this.OnSODETHIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENBAITH", DbType="Int")]
		public System.Nullable<int> TENBAITH
		{
			get
			{
				return this._TENBAITH;
			}
			set
			{
				if ((this._TENBAITH != value))
				{
					if (this._NHOMVK.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnTENBAITHChanging(value);
					this.SendPropertyChanging();
					this._TENBAITH = value;
					this.SendPropertyChanged("TENBAITH");
					this.OnTENBAITHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CAPBAC_SINHVIEN", Storage="_CAPBAC1", ThisKey="CAPBAC", OtherKey="MACAPBAC", IsForeignKey=true, DeleteRule="CASCADE")]
		public CAPBAC CAPBAC1
		{
			get
			{
				return this._CAPBAC1.Entity;
			}
			set
			{
				CAPBAC previousValue = this._CAPBAC1.Entity;
				if (((previousValue != value) 
							|| (this._CAPBAC1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._CAPBAC1.Entity = null;
						previousValue.SINHVIENs.Remove(this);
					}
					this._CAPBAC1.Entity = value;
					if ((value != null))
					{
						value.SINHVIENs.Add(this);
						this._CAPBAC = value.MACAPBAC;
					}
					else
					{
						this._CAPBAC = default(Nullable<int>);
					}
					this.SendPropertyChanged("CAPBAC1");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CHUCVU_SINHVIEN", Storage="_CHUCVU1", ThisKey="CHUCVU", OtherKey="MACHUCVU", IsForeignKey=true, DeleteRule="CASCADE")]
		public CHUCVU CHUCVU1
		{
			get
			{
				return this._CHUCVU1.Entity;
			}
			set
			{
				CHUCVU previousValue = this._CHUCVU1.Entity;
				if (((previousValue != value) 
							|| (this._CHUCVU1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._CHUCVU1.Entity = null;
						previousValue.SINHVIENs.Remove(this);
					}
					this._CHUCVU1.Entity = value;
					if ((value != null))
					{
						value.SINHVIENs.Add(this);
						this._CHUCVU = value.MACHUCVU;
					}
					else
					{
						this._CHUCVU = default(Nullable<int>);
					}
					this.SendPropertyChanged("CHUCVU1");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DETHI_SINHVIEN", Storage="_DETHI", ThisKey="SODETHI", OtherKey="MADETHI", IsForeignKey=true, DeleteRule="CASCADE")]
		public DETHI DETHI
		{
			get
			{
				return this._DETHI.Entity;
			}
			set
			{
				DETHI previousValue = this._DETHI.Entity;
				if (((previousValue != value) 
							|| (this._DETHI.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DETHI.Entity = null;
						previousValue.SINHVIENs.Remove(this);
					}
					this._DETHI.Entity = value;
					if ((value != null))
					{
						value.SINHVIENs.Add(this);
						this._SODETHI = value.MADETHI;
					}
					else
					{
						this._SODETHI = default(Nullable<int>);
					}
					this.SendPropertyChanged("DETHI");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DONVI_SINHVIEN", Storage="_DONVI1", ThisKey="DONVI", OtherKey="MADONVI", IsForeignKey=true, DeleteRule="CASCADE")]
		public DONVI DONVI1
		{
			get
			{
				return this._DONVI1.Entity;
			}
			set
			{
				DONVI previousValue = this._DONVI1.Entity;
				if (((previousValue != value) 
							|| (this._DONVI1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DONVI1.Entity = null;
						previousValue.SINHVIENs.Remove(this);
					}
					this._DONVI1.Entity = value;
					if ((value != null))
					{
						value.SINHVIENs.Add(this);
						this._DONVI = value.MADONVI;
					}
					else
					{
						this._DONVI = default(Nullable<int>);
					}
					this.SendPropertyChanged("DONVI1");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NHOMVK_SINHVIEN", Storage="_NHOMVK", ThisKey="TENBAITH", OtherKey="MANHOM", IsForeignKey=true, DeleteRule="CASCADE")]
		public NHOMVK NHOMVK
		{
			get
			{
				return this._NHOMVK.Entity;
			}
			set
			{
				NHOMVK previousValue = this._NHOMVK.Entity;
				if (((previousValue != value) 
							|| (this._NHOMVK.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NHOMVK.Entity = null;
						previousValue.SINHVIENs.Remove(this);
					}
					this._NHOMVK.Entity = value;
					if ((value != null))
					{
						value.SINHVIENs.Add(this);
						this._TENBAITH = value.MANHOM;
					}
					else
					{
						this._TENBAITH = default(Nullable<int>);
					}
					this.SendPropertyChanged("NHOMVK");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CAPBAC")]
	public partial class CAPBAC : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MACAPBAC;
		
		private string _TENCAPBAC;
		
		private EntitySet<SINHVIEN> _SINHVIENs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMACAPBACChanging(int value);
    partial void OnMACAPBACChanged();
    partial void OnTENCAPBACChanging(string value);
    partial void OnTENCAPBACChanged();
    #endregion
		
		public CAPBAC()
		{
			this._SINHVIENs = new EntitySet<SINHVIEN>(new Action<SINHVIEN>(this.attach_SINHVIENs), new Action<SINHVIEN>(this.detach_SINHVIENs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MACAPBAC", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MACAPBAC
		{
			get
			{
				return this._MACAPBAC;
			}
			set
			{
				if ((this._MACAPBAC != value))
				{
					this.OnMACAPBACChanging(value);
					this.SendPropertyChanging();
					this._MACAPBAC = value;
					this.SendPropertyChanged("MACAPBAC");
					this.OnMACAPBACChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENCAPBAC", DbType="NVarChar(50)")]
		public string TENCAPBAC
		{
			get
			{
				return this._TENCAPBAC;
			}
			set
			{
				if ((this._TENCAPBAC != value))
				{
					this.OnTENCAPBACChanging(value);
					this.SendPropertyChanging();
					this._TENCAPBAC = value;
					this.SendPropertyChanged("TENCAPBAC");
					this.OnTENCAPBACChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CAPBAC_SINHVIEN", Storage="_SINHVIENs", ThisKey="MACAPBAC", OtherKey="CAPBAC")]
		public EntitySet<SINHVIEN> SINHVIENs
		{
			get
			{
				return this._SINHVIENs;
			}
			set
			{
				this._SINHVIENs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_SINHVIENs(SINHVIEN entity)
		{
			this.SendPropertyChanging();
			entity.CAPBAC1 = this;
		}
		
		private void detach_SINHVIENs(SINHVIEN entity)
		{
			this.SendPropertyChanging();
			entity.CAPBAC1 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CHITIETBODETHI")]
	public partial class CHITIETBODETHI : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MABODT;
		
		private int _MACH;
		
		private EntityRef<BODETHI> _BODETHI;
		
		private EntityRef<CAUHOI> _CAUHOI;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMABODTChanging(int value);
    partial void OnMABODTChanged();
    partial void OnMACHChanging(int value);
    partial void OnMACHChanged();
    #endregion
		
		public CHITIETBODETHI()
		{
			this._BODETHI = default(EntityRef<BODETHI>);
			this._CAUHOI = default(EntityRef<CAUHOI>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MABODT", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MABODT
		{
			get
			{
				return this._MABODT;
			}
			set
			{
				if ((this._MABODT != value))
				{
					if (this._BODETHI.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMABODTChanging(value);
					this.SendPropertyChanging();
					this._MABODT = value;
					this.SendPropertyChanged("MABODT");
					this.OnMABODTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MACH", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MACH
		{
			get
			{
				return this._MACH;
			}
			set
			{
				if ((this._MACH != value))
				{
					if (this._CAUHOI.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMACHChanging(value);
					this.SendPropertyChanging();
					this._MACH = value;
					this.SendPropertyChanged("MACH");
					this.OnMACHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="BODETHI_CHITIETBODETHI", Storage="_BODETHI", ThisKey="MABODT", OtherKey="MABODT", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public BODETHI BODETHI
		{
			get
			{
				return this._BODETHI.Entity;
			}
			set
			{
				BODETHI previousValue = this._BODETHI.Entity;
				if (((previousValue != value) 
							|| (this._BODETHI.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._BODETHI.Entity = null;
						previousValue.CHITIETBODETHIs.Remove(this);
					}
					this._BODETHI.Entity = value;
					if ((value != null))
					{
						value.CHITIETBODETHIs.Add(this);
						this._MABODT = value.MABODT;
					}
					else
					{
						this._MABODT = default(int);
					}
					this.SendPropertyChanged("BODETHI");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CAUHOI_CHITIETBODETHI", Storage="_CAUHOI", ThisKey="MACH", OtherKey="MACH", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public CAUHOI CAUHOI
		{
			get
			{
				return this._CAUHOI.Entity;
			}
			set
			{
				CAUHOI previousValue = this._CAUHOI.Entity;
				if (((previousValue != value) 
							|| (this._CAUHOI.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._CAUHOI.Entity = null;
						previousValue.CHITIETBODETHIs.Remove(this);
					}
					this._CAUHOI.Entity = value;
					if ((value != null))
					{
						value.CHITIETBODETHIs.Add(this);
						this._MACH = value.MACH;
					}
					else
					{
						this._MACH = default(int);
					}
					this.SendPropertyChanged("CAUHOI");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CHITIETDETHI")]
	public partial class CHITIETDETHI : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MADETHI;
		
		private int _MACH;
		
		private string _DA;
		
		private EntityRef<DETHI> _DETHI;
		
		private EntityRef<CAUHOI> _CAUHOI;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMADETHIChanging(int value);
    partial void OnMADETHIChanged();
    partial void OnMACHChanging(int value);
    partial void OnMACHChanged();
    partial void OnDAChanging(string value);
    partial void OnDAChanged();
    #endregion
		
		public CHITIETDETHI()
		{
			this._DETHI = default(EntityRef<DETHI>);
			this._CAUHOI = default(EntityRef<CAUHOI>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MADETHI", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MADETHI
		{
			get
			{
				return this._MADETHI;
			}
			set
			{
				if ((this._MADETHI != value))
				{
					if (this._DETHI.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMADETHIChanging(value);
					this.SendPropertyChanging();
					this._MADETHI = value;
					this.SendPropertyChanged("MADETHI");
					this.OnMADETHIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MACH", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MACH
		{
			get
			{
				return this._MACH;
			}
			set
			{
				if ((this._MACH != value))
				{
					if (this._CAUHOI.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMACHChanging(value);
					this.SendPropertyChanging();
					this._MACH = value;
					this.SendPropertyChanged("MACH");
					this.OnMACHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DA", DbType="NVarChar(50)")]
		public string DA
		{
			get
			{
				return this._DA;
			}
			set
			{
				if ((this._DA != value))
				{
					this.OnDAChanging(value);
					this.SendPropertyChanging();
					this._DA = value;
					this.SendPropertyChanged("DA");
					this.OnDAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DETHI_CHITIETDETHI", Storage="_DETHI", ThisKey="MADETHI", OtherKey="MADETHI", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public DETHI DETHI
		{
			get
			{
				return this._DETHI.Entity;
			}
			set
			{
				DETHI previousValue = this._DETHI.Entity;
				if (((previousValue != value) 
							|| (this._DETHI.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DETHI.Entity = null;
						previousValue.CHITIETDETHIs.Remove(this);
					}
					this._DETHI.Entity = value;
					if ((value != null))
					{
						value.CHITIETDETHIs.Add(this);
						this._MADETHI = value.MADETHI;
					}
					else
					{
						this._MADETHI = default(int);
					}
					this.SendPropertyChanged("DETHI");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CAUHOI_CHITIETDETHI", Storage="_CAUHOI", ThisKey="MACH", OtherKey="MACH", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public CAUHOI CAUHOI
		{
			get
			{
				return this._CAUHOI.Entity;
			}
			set
			{
				CAUHOI previousValue = this._CAUHOI.Entity;
				if (((previousValue != value) 
							|| (this._CAUHOI.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._CAUHOI.Entity = null;
						previousValue.CHITIETDETHIs.Remove(this);
					}
					this._CAUHOI.Entity = value;
					if ((value != null))
					{
						value.CHITIETDETHIs.Add(this);
						this._MACH = value.MACH;
					}
					else
					{
						this._MACH = default(int);
					}
					this.SendPropertyChanged("CAUHOI");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CHUCVU")]
	public partial class CHUCVU : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MACHUCVU;
		
		private string _TENCHUCVU;
		
		private EntitySet<SINHVIEN> _SINHVIENs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMACHUCVUChanging(int value);
    partial void OnMACHUCVUChanged();
    partial void OnTENCHUCVUChanging(string value);
    partial void OnTENCHUCVUChanged();
    #endregion
		
		public CHUCVU()
		{
			this._SINHVIENs = new EntitySet<SINHVIEN>(new Action<SINHVIEN>(this.attach_SINHVIENs), new Action<SINHVIEN>(this.detach_SINHVIENs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MACHUCVU", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MACHUCVU
		{
			get
			{
				return this._MACHUCVU;
			}
			set
			{
				if ((this._MACHUCVU != value))
				{
					this.OnMACHUCVUChanging(value);
					this.SendPropertyChanging();
					this._MACHUCVU = value;
					this.SendPropertyChanged("MACHUCVU");
					this.OnMACHUCVUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENCHUCVU", DbType="NVarChar(50)")]
		public string TENCHUCVU
		{
			get
			{
				return this._TENCHUCVU;
			}
			set
			{
				if ((this._TENCHUCVU != value))
				{
					this.OnTENCHUCVUChanging(value);
					this.SendPropertyChanging();
					this._TENCHUCVU = value;
					this.SendPropertyChanged("TENCHUCVU");
					this.OnTENCHUCVUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CHUCVU_SINHVIEN", Storage="_SINHVIENs", ThisKey="MACHUCVU", OtherKey="CHUCVU")]
		public EntitySet<SINHVIEN> SINHVIENs
		{
			get
			{
				return this._SINHVIENs;
			}
			set
			{
				this._SINHVIENs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_SINHVIENs(SINHVIEN entity)
		{
			this.SendPropertyChanging();
			entity.CHUCVU1 = this;
		}
		
		private void detach_SINHVIENs(SINHVIEN entity)
		{
			this.SendPropertyChanging();
			entity.CHUCVU1 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DETHI")]
	public partial class DETHI : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MADETHI;
		
		private System.Nullable<System.DateTime> _NGAYTAO;
		
		private System.Nullable<int> _MAKYTHI;
		
		private EntitySet<SINHVIEN> _SINHVIENs;
		
		private EntitySet<CHITIETDETHI> _CHITIETDETHIs;
		
		private EntityRef<KYTHI> _KYTHI;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMADETHIChanging(int value);
    partial void OnMADETHIChanged();
    partial void OnNGAYTAOChanging(System.Nullable<System.DateTime> value);
    partial void OnNGAYTAOChanged();
    partial void OnMAKYTHIChanging(System.Nullable<int> value);
    partial void OnMAKYTHIChanged();
    #endregion
		
		public DETHI()
		{
			this._SINHVIENs = new EntitySet<SINHVIEN>(new Action<SINHVIEN>(this.attach_SINHVIENs), new Action<SINHVIEN>(this.detach_SINHVIENs));
			this._CHITIETDETHIs = new EntitySet<CHITIETDETHI>(new Action<CHITIETDETHI>(this.attach_CHITIETDETHIs), new Action<CHITIETDETHI>(this.detach_CHITIETDETHIs));
			this._KYTHI = default(EntityRef<KYTHI>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MADETHI", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MADETHI
		{
			get
			{
				return this._MADETHI;
			}
			set
			{
				if ((this._MADETHI != value))
				{
					this.OnMADETHIChanging(value);
					this.SendPropertyChanging();
					this._MADETHI = value;
					this.SendPropertyChanged("MADETHI");
					this.OnMADETHIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAYTAO", DbType="Date")]
		public System.Nullable<System.DateTime> NGAYTAO
		{
			get
			{
				return this._NGAYTAO;
			}
			set
			{
				if ((this._NGAYTAO != value))
				{
					this.OnNGAYTAOChanging(value);
					this.SendPropertyChanging();
					this._NGAYTAO = value;
					this.SendPropertyChanged("NGAYTAO");
					this.OnNGAYTAOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAKYTHI", DbType="Int")]
		public System.Nullable<int> MAKYTHI
		{
			get
			{
				return this._MAKYTHI;
			}
			set
			{
				if ((this._MAKYTHI != value))
				{
					if (this._KYTHI.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMAKYTHIChanging(value);
					this.SendPropertyChanging();
					this._MAKYTHI = value;
					this.SendPropertyChanged("MAKYTHI");
					this.OnMAKYTHIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DETHI_SINHVIEN", Storage="_SINHVIENs", ThisKey="MADETHI", OtherKey="SODETHI")]
		public EntitySet<SINHVIEN> SINHVIENs
		{
			get
			{
				return this._SINHVIENs;
			}
			set
			{
				this._SINHVIENs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DETHI_CHITIETDETHI", Storage="_CHITIETDETHIs", ThisKey="MADETHI", OtherKey="MADETHI")]
		public EntitySet<CHITIETDETHI> CHITIETDETHIs
		{
			get
			{
				return this._CHITIETDETHIs;
			}
			set
			{
				this._CHITIETDETHIs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KYTHI_DETHI", Storage="_KYTHI", ThisKey="MAKYTHI", OtherKey="MAKYTHI", IsForeignKey=true, DeleteRule="CASCADE")]
		public KYTHI KYTHI
		{
			get
			{
				return this._KYTHI.Entity;
			}
			set
			{
				KYTHI previousValue = this._KYTHI.Entity;
				if (((previousValue != value) 
							|| (this._KYTHI.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._KYTHI.Entity = null;
						previousValue.DETHIs.Remove(this);
					}
					this._KYTHI.Entity = value;
					if ((value != null))
					{
						value.DETHIs.Add(this);
						this._MAKYTHI = value.MAKYTHI;
					}
					else
					{
						this._MAKYTHI = default(Nullable<int>);
					}
					this.SendPropertyChanged("KYTHI");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_SINHVIENs(SINHVIEN entity)
		{
			this.SendPropertyChanging();
			entity.DETHI = this;
		}
		
		private void detach_SINHVIENs(SINHVIEN entity)
		{
			this.SendPropertyChanging();
			entity.DETHI = null;
		}
		
		private void attach_CHITIETDETHIs(CHITIETDETHI entity)
		{
			this.SendPropertyChanging();
			entity.DETHI = this;
		}
		
		private void detach_CHITIETDETHIs(CHITIETDETHI entity)
		{
			this.SendPropertyChanging();
			entity.DETHI = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DETHI_SINHVIEN")]
	public partial class DETHI_SINHVIEN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MATS;
		
		private int _MADETHI;
		
		private System.Nullable<int> _TENBAITH;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMATSChanging(string value);
    partial void OnMATSChanged();
    partial void OnMADETHIChanging(int value);
    partial void OnMADETHIChanged();
    partial void OnTENBAITHChanging(System.Nullable<int> value);
    partial void OnTENBAITHChanged();
    #endregion
		
		public DETHI_SINHVIEN()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MATS", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MATS
		{
			get
			{
				return this._MATS;
			}
			set
			{
				if ((this._MATS != value))
				{
					this.OnMATSChanging(value);
					this.SendPropertyChanging();
					this._MATS = value;
					this.SendPropertyChanged("MATS");
					this.OnMATSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MADETHI", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MADETHI
		{
			get
			{
				return this._MADETHI;
			}
			set
			{
				if ((this._MADETHI != value))
				{
					this.OnMADETHIChanging(value);
					this.SendPropertyChanging();
					this._MADETHI = value;
					this.SendPropertyChanged("MADETHI");
					this.OnMADETHIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENBAITH", DbType="Int")]
		public System.Nullable<int> TENBAITH
		{
			get
			{
				return this._TENBAITH;
			}
			set
			{
				if ((this._TENBAITH != value))
				{
					this.OnTENBAITHChanging(value);
					this.SendPropertyChanging();
					this._TENBAITH = value;
					this.SendPropertyChanged("TENBAITH");
					this.OnTENBAITHChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DONVI")]
	public partial class DONVI : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MADONVI;
		
		private string _TENDONVI;
		
		private EntitySet<SINHVIEN> _SINHVIENs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMADONVIChanging(int value);
    partial void OnMADONVIChanged();
    partial void OnTENDONVIChanging(string value);
    partial void OnTENDONVIChanged();
    #endregion
		
		public DONVI()
		{
			this._SINHVIENs = new EntitySet<SINHVIEN>(new Action<SINHVIEN>(this.attach_SINHVIENs), new Action<SINHVIEN>(this.detach_SINHVIENs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MADONVI", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MADONVI
		{
			get
			{
				return this._MADONVI;
			}
			set
			{
				if ((this._MADONVI != value))
				{
					this.OnMADONVIChanging(value);
					this.SendPropertyChanging();
					this._MADONVI = value;
					this.SendPropertyChanged("MADONVI");
					this.OnMADONVIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENDONVI", DbType="NVarChar(50)")]
		public string TENDONVI
		{
			get
			{
				return this._TENDONVI;
			}
			set
			{
				if ((this._TENDONVI != value))
				{
					this.OnTENDONVIChanging(value);
					this.SendPropertyChanging();
					this._TENDONVI = value;
					this.SendPropertyChanged("TENDONVI");
					this.OnTENDONVIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DONVI_SINHVIEN", Storage="_SINHVIENs", ThisKey="MADONVI", OtherKey="DONVI")]
		public EntitySet<SINHVIEN> SINHVIENs
		{
			get
			{
				return this._SINHVIENs;
			}
			set
			{
				this._SINHVIENs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_SINHVIENs(SINHVIEN entity)
		{
			this.SendPropertyChanging();
			entity.DONVI1 = this;
		}
		
		private void detach_SINHVIENs(SINHVIEN entity)
		{
			this.SendPropertyChanging();
			entity.DONVI1 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KETQUA")]
	public partial class KETQUA : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MATS;
		
		private System.DateTime _NGAYTHI;
		
		private System.Nullable<int> _SOCAUDUNG;
		
		private System.Nullable<int> _SOCAUSAI;
		
		private System.Nullable<int> _DIEM;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMATSChanging(string value);
    partial void OnMATSChanged();
    partial void OnNGAYTHIChanging(System.DateTime value);
    partial void OnNGAYTHIChanged();
    partial void OnSOCAUDUNGChanging(System.Nullable<int> value);
    partial void OnSOCAUDUNGChanged();
    partial void OnSOCAUSAIChanging(System.Nullable<int> value);
    partial void OnSOCAUSAIChanged();
    partial void OnDIEMChanging(System.Nullable<int> value);
    partial void OnDIEMChanged();
    #endregion
		
		public KETQUA()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MATS", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MATS
		{
			get
			{
				return this._MATS;
			}
			set
			{
				if ((this._MATS != value))
				{
					this.OnMATSChanging(value);
					this.SendPropertyChanging();
					this._MATS = value;
					this.SendPropertyChanged("MATS");
					this.OnMATSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAYTHI", DbType="DateTime NOT NULL")]
		public System.DateTime NGAYTHI
		{
			get
			{
				return this._NGAYTHI;
			}
			set
			{
				if ((this._NGAYTHI != value))
				{
					this.OnNGAYTHIChanging(value);
					this.SendPropertyChanging();
					this._NGAYTHI = value;
					this.SendPropertyChanged("NGAYTHI");
					this.OnNGAYTHIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SOCAUDUNG", DbType="Int")]
		public System.Nullable<int> SOCAUDUNG
		{
			get
			{
				return this._SOCAUDUNG;
			}
			set
			{
				if ((this._SOCAUDUNG != value))
				{
					this.OnSOCAUDUNGChanging(value);
					this.SendPropertyChanging();
					this._SOCAUDUNG = value;
					this.SendPropertyChanged("SOCAUDUNG");
					this.OnSOCAUDUNGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SOCAUSAI", DbType="Int")]
		public System.Nullable<int> SOCAUSAI
		{
			get
			{
				return this._SOCAUSAI;
			}
			set
			{
				if ((this._SOCAUSAI != value))
				{
					this.OnSOCAUSAIChanging(value);
					this.SendPropertyChanging();
					this._SOCAUSAI = value;
					this.SendPropertyChanged("SOCAUSAI");
					this.OnSOCAUSAIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIEM", DbType="Int")]
		public System.Nullable<int> DIEM
		{
			get
			{
				return this._DIEM;
			}
			set
			{
				if ((this._DIEM != value))
				{
					this.OnDIEMChanging(value);
					this.SendPropertyChanging();
					this._DIEM = value;
					this.SendPropertyChanged("DIEM");
					this.OnDIEMChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KYTHI")]
	public partial class KYTHI : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MAKYTHI;
		
		private string _TENKYTHI;
		
		private System.Nullable<System.DateTime> _NGAYTHI;
		
		private System.Nullable<int> _MABODT;
		
		private System.Nullable<int> _SODETHI;
		
		private EntitySet<DETHI> _DETHIs;
		
		private EntityRef<BODETHI> _BODETHI;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMAKYTHIChanging(int value);
    partial void OnMAKYTHIChanged();
    partial void OnTENKYTHIChanging(string value);
    partial void OnTENKYTHIChanged();
    partial void OnNGAYTHIChanging(System.Nullable<System.DateTime> value);
    partial void OnNGAYTHIChanged();
    partial void OnMABODTChanging(System.Nullable<int> value);
    partial void OnMABODTChanged();
    partial void OnSODETHIChanging(System.Nullable<int> value);
    partial void OnSODETHIChanged();
    #endregion
		
		public KYTHI()
		{
			this._DETHIs = new EntitySet<DETHI>(new Action<DETHI>(this.attach_DETHIs), new Action<DETHI>(this.detach_DETHIs));
			this._BODETHI = default(EntityRef<BODETHI>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAKYTHI", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MAKYTHI
		{
			get
			{
				return this._MAKYTHI;
			}
			set
			{
				if ((this._MAKYTHI != value))
				{
					this.OnMAKYTHIChanging(value);
					this.SendPropertyChanging();
					this._MAKYTHI = value;
					this.SendPropertyChanged("MAKYTHI");
					this.OnMAKYTHIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENKYTHI", DbType="NVarChar(50)")]
		public string TENKYTHI
		{
			get
			{
				return this._TENKYTHI;
			}
			set
			{
				if ((this._TENKYTHI != value))
				{
					this.OnTENKYTHIChanging(value);
					this.SendPropertyChanging();
					this._TENKYTHI = value;
					this.SendPropertyChanged("TENKYTHI");
					this.OnTENKYTHIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAYTHI", DbType="Date")]
		public System.Nullable<System.DateTime> NGAYTHI
		{
			get
			{
				return this._NGAYTHI;
			}
			set
			{
				if ((this._NGAYTHI != value))
				{
					this.OnNGAYTHIChanging(value);
					this.SendPropertyChanging();
					this._NGAYTHI = value;
					this.SendPropertyChanged("NGAYTHI");
					this.OnNGAYTHIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MABODT", DbType="Int")]
		public System.Nullable<int> MABODT
		{
			get
			{
				return this._MABODT;
			}
			set
			{
				if ((this._MABODT != value))
				{
					if (this._BODETHI.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMABODTChanging(value);
					this.SendPropertyChanging();
					this._MABODT = value;
					this.SendPropertyChanged("MABODT");
					this.OnMABODTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SODETHI", DbType="Int")]
		public System.Nullable<int> SODETHI
		{
			get
			{
				return this._SODETHI;
			}
			set
			{
				if ((this._SODETHI != value))
				{
					this.OnSODETHIChanging(value);
					this.SendPropertyChanging();
					this._SODETHI = value;
					this.SendPropertyChanged("SODETHI");
					this.OnSODETHIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KYTHI_DETHI", Storage="_DETHIs", ThisKey="MAKYTHI", OtherKey="MAKYTHI")]
		public EntitySet<DETHI> DETHIs
		{
			get
			{
				return this._DETHIs;
			}
			set
			{
				this._DETHIs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="BODETHI_KYTHI", Storage="_BODETHI", ThisKey="MABODT", OtherKey="MABODT", IsForeignKey=true, DeleteRule="CASCADE")]
		public BODETHI BODETHI
		{
			get
			{
				return this._BODETHI.Entity;
			}
			set
			{
				BODETHI previousValue = this._BODETHI.Entity;
				if (((previousValue != value) 
							|| (this._BODETHI.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._BODETHI.Entity = null;
						previousValue.KYTHIs.Remove(this);
					}
					this._BODETHI.Entity = value;
					if ((value != null))
					{
						value.KYTHIs.Add(this);
						this._MABODT = value.MABODT;
					}
					else
					{
						this._MABODT = default(Nullable<int>);
					}
					this.SendPropertyChanged("BODETHI");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DETHIs(DETHI entity)
		{
			this.SendPropertyChanging();
			entity.KYTHI = this;
		}
		
		private void detach_DETHIs(DETHI entity)
		{
			this.SendPropertyChanging();
			entity.KYTHI = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LOADKQCU")]
	public partial class LOADKQCU
	{
		
		private string _TENTS;
		
		private string _TRINHDO;
		
		private string _SOCH;
		
		private string _THOIGIAN;
		
		private System.Nullable<int> _SOCAUDUNG;
		
		private System.Nullable<int> _SOCAUSAI;
		
		private System.Nullable<System.DateTime> _NGAYTHI;
		
		public LOADKQCU()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENTS", DbType="NVarChar(50)")]
		public string TENTS
		{
			get
			{
				return this._TENTS;
			}
			set
			{
				if ((this._TENTS != value))
				{
					this._TENTS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TRINHDO", DbType="NVarChar(50)")]
		public string TRINHDO
		{
			get
			{
				return this._TRINHDO;
			}
			set
			{
				if ((this._TRINHDO != value))
				{
					this._TRINHDO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SOCH", DbType="NVarChar(50)")]
		public string SOCH
		{
			get
			{
				return this._SOCH;
			}
			set
			{
				if ((this._SOCH != value))
				{
					this._SOCH = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_THOIGIAN", DbType="NVarChar(50)")]
		public string THOIGIAN
		{
			get
			{
				return this._THOIGIAN;
			}
			set
			{
				if ((this._THOIGIAN != value))
				{
					this._THOIGIAN = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SOCAUDUNG", DbType="Int")]
		public System.Nullable<int> SOCAUDUNG
		{
			get
			{
				return this._SOCAUDUNG;
			}
			set
			{
				if ((this._SOCAUDUNG != value))
				{
					this._SOCAUDUNG = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SOCAUSAI", DbType="Int")]
		public System.Nullable<int> SOCAUSAI
		{
			get
			{
				return this._SOCAUSAI;
			}
			set
			{
				if ((this._SOCAUSAI != value))
				{
					this._SOCAUSAI = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAYTHI", DbType="DateTime")]
		public System.Nullable<System.DateTime> NGAYTHI
		{
			get
			{
				return this._NGAYTHI;
			}
			set
			{
				if ((this._NGAYTHI != value))
				{
					this._NGAYTHI = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NHOMVK")]
	public partial class NHOMVK : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MANHOM;
		
		private string _TENNHOM;
		
		private EntitySet<SINHVIEN> _SINHVIENs;
		
		private EntitySet<CAUHOI> _CAUHOIs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMANHOMChanging(int value);
    partial void OnMANHOMChanged();
    partial void OnTENNHOMChanging(string value);
    partial void OnTENNHOMChanged();
    #endregion
		
		public NHOMVK()
		{
			this._SINHVIENs = new EntitySet<SINHVIEN>(new Action<SINHVIEN>(this.attach_SINHVIENs), new Action<SINHVIEN>(this.detach_SINHVIENs));
			this._CAUHOIs = new EntitySet<CAUHOI>(new Action<CAUHOI>(this.attach_CAUHOIs), new Action<CAUHOI>(this.detach_CAUHOIs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MANHOM", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MANHOM
		{
			get
			{
				return this._MANHOM;
			}
			set
			{
				if ((this._MANHOM != value))
				{
					this.OnMANHOMChanging(value);
					this.SendPropertyChanging();
					this._MANHOM = value;
					this.SendPropertyChanged("MANHOM");
					this.OnMANHOMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENNHOM", DbType="NVarChar(100)")]
		public string TENNHOM
		{
			get
			{
				return this._TENNHOM;
			}
			set
			{
				if ((this._TENNHOM != value))
				{
					this.OnTENNHOMChanging(value);
					this.SendPropertyChanging();
					this._TENNHOM = value;
					this.SendPropertyChanged("TENNHOM");
					this.OnTENNHOMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NHOMVK_SINHVIEN", Storage="_SINHVIENs", ThisKey="MANHOM", OtherKey="TENBAITH")]
		public EntitySet<SINHVIEN> SINHVIENs
		{
			get
			{
				return this._SINHVIENs;
			}
			set
			{
				this._SINHVIENs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NHOMVK_CAUHOI", Storage="_CAUHOIs", ThisKey="MANHOM", OtherKey="MANHOM")]
		public EntitySet<CAUHOI> CAUHOIs
		{
			get
			{
				return this._CAUHOIs;
			}
			set
			{
				this._CAUHOIs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_SINHVIENs(SINHVIEN entity)
		{
			this.SendPropertyChanging();
			entity.NHOMVK = this;
		}
		
		private void detach_SINHVIENs(SINHVIEN entity)
		{
			this.SendPropertyChanging();
			entity.NHOMVK = null;
		}
		
		private void attach_CAUHOIs(CAUHOI entity)
		{
			this.SendPropertyChanging();
			entity.NHOMVK = this;
		}
		
		private void detach_CAUHOIs(CAUHOI entity)
		{
			this.SendPropertyChanging();
			entity.NHOMVK = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.BODETHI_CAUHOI")]
	public partial class BODETHI_CAUHOI
	{
		
		private int _MABODT;
		
		private int _MACH;
		
		private string _NOIDUNG;
		
		private string _HINHANH;
		
		private int _MANHOM;
		
		public BODETHI_CAUHOI()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MABODT", DbType="Int NOT NULL")]
		public int MABODT
		{
			get
			{
				return this._MABODT;
			}
			set
			{
				if ((this._MABODT != value))
				{
					this._MABODT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MACH", DbType="Int NOT NULL")]
		public int MACH
		{
			get
			{
				return this._MACH;
			}
			set
			{
				if ((this._MACH != value))
				{
					this._MACH = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOIDUNG", DbType="NVarChar(255)")]
		public string NOIDUNG
		{
			get
			{
				return this._NOIDUNG;
			}
			set
			{
				if ((this._NOIDUNG != value))
				{
					this._NOIDUNG = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HINHANH", DbType="NVarChar(50)")]
		public string HINHANH
		{
			get
			{
				return this._HINHANH;
			}
			set
			{
				if ((this._HINHANH != value))
				{
					this._HINHANH = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MANHOM", DbType="Int NOT NULL")]
		public int MANHOM
		{
			get
			{
				return this._MANHOM;
			}
			set
			{
				if ((this._MANHOM != value))
				{
					this._MANHOM = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CAUHOI")]
	public partial class CAUHOI : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MACH;
		
		private string _NOIDUNG;
		
		private string _HINHANH;
		
		private System.Nullable<int> _MANHOM;
		
		private EntitySet<CHITIETBODETHI> _CHITIETBODETHIs;
		
		private EntitySet<CHITIETDETHI> _CHITIETDETHIs;
		
		private EntitySet<DAPAN> _DAPANs;
		
		private EntityRef<NHOMVK> _NHOMVK;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMACHChanging(int value);
    partial void OnMACHChanged();
    partial void OnNOIDUNGChanging(string value);
    partial void OnNOIDUNGChanged();
    partial void OnHINHANHChanging(string value);
    partial void OnHINHANHChanged();
    partial void OnMANHOMChanging(System.Nullable<int> value);
    partial void OnMANHOMChanged();
    #endregion
		
		public CAUHOI()
		{
			this._CHITIETBODETHIs = new EntitySet<CHITIETBODETHI>(new Action<CHITIETBODETHI>(this.attach_CHITIETBODETHIs), new Action<CHITIETBODETHI>(this.detach_CHITIETBODETHIs));
			this._CHITIETDETHIs = new EntitySet<CHITIETDETHI>(new Action<CHITIETDETHI>(this.attach_CHITIETDETHIs), new Action<CHITIETDETHI>(this.detach_CHITIETDETHIs));
			this._DAPANs = new EntitySet<DAPAN>(new Action<DAPAN>(this.attach_DAPANs), new Action<DAPAN>(this.detach_DAPANs));
			this._NHOMVK = default(EntityRef<NHOMVK>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MACH", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MACH
		{
			get
			{
				return this._MACH;
			}
			set
			{
				if ((this._MACH != value))
				{
					this.OnMACHChanging(value);
					this.SendPropertyChanging();
					this._MACH = value;
					this.SendPropertyChanged("MACH");
					this.OnMACHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOIDUNG", DbType="NVarChar(500)")]
		public string NOIDUNG
		{
			get
			{
				return this._NOIDUNG;
			}
			set
			{
				if ((this._NOIDUNG != value))
				{
					this.OnNOIDUNGChanging(value);
					this.SendPropertyChanging();
					this._NOIDUNG = value;
					this.SendPropertyChanged("NOIDUNG");
					this.OnNOIDUNGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HINHANH", DbType="NVarChar(50)")]
		public string HINHANH
		{
			get
			{
				return this._HINHANH;
			}
			set
			{
				if ((this._HINHANH != value))
				{
					this.OnHINHANHChanging(value);
					this.SendPropertyChanging();
					this._HINHANH = value;
					this.SendPropertyChanged("HINHANH");
					this.OnHINHANHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MANHOM", DbType="Int")]
		public System.Nullable<int> MANHOM
		{
			get
			{
				return this._MANHOM;
			}
			set
			{
				if ((this._MANHOM != value))
				{
					if (this._NHOMVK.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMANHOMChanging(value);
					this.SendPropertyChanging();
					this._MANHOM = value;
					this.SendPropertyChanged("MANHOM");
					this.OnMANHOMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CAUHOI_CHITIETBODETHI", Storage="_CHITIETBODETHIs", ThisKey="MACH", OtherKey="MACH")]
		public EntitySet<CHITIETBODETHI> CHITIETBODETHIs
		{
			get
			{
				return this._CHITIETBODETHIs;
			}
			set
			{
				this._CHITIETBODETHIs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CAUHOI_CHITIETDETHI", Storage="_CHITIETDETHIs", ThisKey="MACH", OtherKey="MACH")]
		public EntitySet<CHITIETDETHI> CHITIETDETHIs
		{
			get
			{
				return this._CHITIETDETHIs;
			}
			set
			{
				this._CHITIETDETHIs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CAUHOI_DAPAN", Storage="_DAPANs", ThisKey="MACH", OtherKey="MACH")]
		public EntitySet<DAPAN> DAPANs
		{
			get
			{
				return this._DAPANs;
			}
			set
			{
				this._DAPANs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NHOMVK_CAUHOI", Storage="_NHOMVK", ThisKey="MANHOM", OtherKey="MANHOM", IsForeignKey=true, DeleteRule="CASCADE")]
		public NHOMVK NHOMVK
		{
			get
			{
				return this._NHOMVK.Entity;
			}
			set
			{
				NHOMVK previousValue = this._NHOMVK.Entity;
				if (((previousValue != value) 
							|| (this._NHOMVK.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NHOMVK.Entity = null;
						previousValue.CAUHOIs.Remove(this);
					}
					this._NHOMVK.Entity = value;
					if ((value != null))
					{
						value.CAUHOIs.Add(this);
						this._MANHOM = value.MANHOM;
					}
					else
					{
						this._MANHOM = default(Nullable<int>);
					}
					this.SendPropertyChanged("NHOMVK");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CHITIETBODETHIs(CHITIETBODETHI entity)
		{
			this.SendPropertyChanging();
			entity.CAUHOI = this;
		}
		
		private void detach_CHITIETBODETHIs(CHITIETBODETHI entity)
		{
			this.SendPropertyChanging();
			entity.CAUHOI = null;
		}
		
		private void attach_CHITIETDETHIs(CHITIETDETHI entity)
		{
			this.SendPropertyChanging();
			entity.CAUHOI = this;
		}
		
		private void detach_CHITIETDETHIs(CHITIETDETHI entity)
		{
			this.SendPropertyChanging();
			entity.CAUHOI = null;
		}
		
		private void attach_DAPANs(DAPAN entity)
		{
			this.SendPropertyChanging();
			entity.CAUHOI = this;
		}
		
		private void detach_DAPANs(DAPAN entity)
		{
			this.SendPropertyChanging();
			entity.CAUHOI = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DAPAN")]
	public partial class DAPAN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MADA;
		
		private System.Nullable<int> _MACH;
		
		private string _NOIDUNGDA;
		
		private System.Nullable<bool> _DADUNG;
		
		private EntityRef<CAUHOI> _CAUHOI;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMADAChanging(int value);
    partial void OnMADAChanged();
    partial void OnMACHChanging(System.Nullable<int> value);
    partial void OnMACHChanged();
    partial void OnNOIDUNGDAChanging(string value);
    partial void OnNOIDUNGDAChanged();
    partial void OnDADUNGChanging(System.Nullable<bool> value);
    partial void OnDADUNGChanged();
    #endregion
		
		public DAPAN()
		{
			this._CAUHOI = default(EntityRef<CAUHOI>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MADA", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MADA
		{
			get
			{
				return this._MADA;
			}
			set
			{
				if ((this._MADA != value))
				{
					this.OnMADAChanging(value);
					this.SendPropertyChanging();
					this._MADA = value;
					this.SendPropertyChanged("MADA");
					this.OnMADAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MACH", DbType="Int")]
		public System.Nullable<int> MACH
		{
			get
			{
				return this._MACH;
			}
			set
			{
				if ((this._MACH != value))
				{
					if (this._CAUHOI.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMACHChanging(value);
					this.SendPropertyChanging();
					this._MACH = value;
					this.SendPropertyChanged("MACH");
					this.OnMACHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOIDUNGDA", DbType="NVarChar(500)")]
		public string NOIDUNGDA
		{
			get
			{
				return this._NOIDUNGDA;
			}
			set
			{
				if ((this._NOIDUNGDA != value))
				{
					this.OnNOIDUNGDAChanging(value);
					this.SendPropertyChanging();
					this._NOIDUNGDA = value;
					this.SendPropertyChanged("NOIDUNGDA");
					this.OnNOIDUNGDAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DADUNG", DbType="Bit")]
		public System.Nullable<bool> DADUNG
		{
			get
			{
				return this._DADUNG;
			}
			set
			{
				if ((this._DADUNG != value))
				{
					this.OnDADUNGChanging(value);
					this.SendPropertyChanging();
					this._DADUNG = value;
					this.SendPropertyChanged("DADUNG");
					this.OnDADUNGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CAUHOI_DAPAN", Storage="_CAUHOI", ThisKey="MACH", OtherKey="MACH", IsForeignKey=true, DeleteRule="CASCADE")]
		public CAUHOI CAUHOI
		{
			get
			{
				return this._CAUHOI.Entity;
			}
			set
			{
				CAUHOI previousValue = this._CAUHOI.Entity;
				if (((previousValue != value) 
							|| (this._CAUHOI.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._CAUHOI.Entity = null;
						previousValue.DAPANs.Remove(this);
					}
					this._CAUHOI.Entity = value;
					if ((value != null))
					{
						value.DAPANs.Add(this);
						this._MACH = value.MACH;
					}
					else
					{
						this._MACH = default(Nullable<int>);
					}
					this.SendPropertyChanged("CAUHOI");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	public partial class sp_DanhSachCauHoiDeThiResult
	{
		
		private int _mach;
		
		private string _noidung;
		
		private System.Nullable<int> _manhom;
		
		private string _noidungda;
		
		public sp_DanhSachCauHoiDeThiResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mach", DbType="Int NOT NULL")]
		public int mach
		{
			get
			{
				return this._mach;
			}
			set
			{
				if ((this._mach != value))
				{
					this._mach = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_noidung", DbType="NVarChar(500)")]
		public string noidung
		{
			get
			{
				return this._noidung;
			}
			set
			{
				if ((this._noidung != value))
				{
					this._noidung = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_manhom", DbType="Int")]
		public System.Nullable<int> manhom
		{
			get
			{
				return this._manhom;
			}
			set
			{
				if ((this._manhom != value))
				{
					this._manhom = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_noidungda", DbType="NVarChar(500)")]
		public string noidungda
		{
			get
			{
				return this._noidungda;
			}
			set
			{
				if ((this._noidungda != value))
				{
					this._noidungda = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
